# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i -g yarn
  # install modules and build
  - yarn

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - yarn --version
  # run tests
  - npm test

after_test:
  - node example.js

# Don't actually build.
build: off